import Head from 'next/head'
import Link from 'next/link'
import { MainLayout } from '../../components/layouts/MainLayout'
import { Navbar } from '../../components/Navbar'

export default function ContactPage() {
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Contact - JC</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <Navbar />

    //   <main className={styles.main}>
        
    //     <h1>Contact Page</h1>

    //     <h1 className={styles.title}>
    //       Ir a <a href="/about">About</a>
    //       Ir a <Link href="/">Home</Link> o <Link href="/about">About</Link>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/contact.jsx</code>
    //     </p>
    //   </main>
    // </div>
    <MainLayout>
      <h1>Contact Page</h1>

      <h1 className={'title'}>
        {/* Ir a <a href="/about">About</a> */}
        Ir a <Link href="/">Home</Link> o <Link href="/about">About</Link>
      </h1>

      <p className={'description'}>
        Get started by editing{' '}
        <code className={'code'}>pages/contact/index.jsx</code>
      </p>
    </MainLayout>

  )
}