
import Link from 'next/link'
import { MainLayout } from '../components/layouts/MainLayout'

export default function HomePage() {
  return (
    // <div className={styles.container}>
    //   <Head>
    //     <title>Home - JC</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <Navbar />

    //   <main className={styles.main}>
        
    //     <h1>Home Page</h1>

    //     <h1 className={styles.title}>
    //       Ir a <a href="/about">About</a>
    //       Ir a <Link href="/about">About</Link>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/index.jsx</code>
    //     </p>
    //   </main>
    // </div>
    <MainLayout>
      <h1>Home Page</h1>

      <h1 className={'title'}>
        {/* Ir a <a href="/about">About</a> */}
        Ir a <Link href="/about">About</Link>
      </h1>

      <p className={'description'}>
        Get started by editing{' '}
        <code className={'code'}>pages/index.jsx</code>
      </p>
    </MainLayout>
  )
}
