import Head from 'next/head';
import { FC } from 'react';
import { PropsChildren } from '../interfaces/props';

import { Navbar } from '../Navbar';

import styles from './MainLayout.module.css';

export const MainLayout: FC<PropsChildren> = ({ children }) => {
    return (
        <div className={styles.container}>
          <Head>
            <title>Home - JC</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <Navbar />
    
          <main className={styles.main}>
            
            { children }
            
          </main>
        </div>
      )
}
